### ISSUE TITLE
KeyPress and KeyDown doesnt trigger on ALT 

### ISSUE THREAD

**Issue by DomEscobar** [ROGR3/LepikJS#11] opened 2023-09-19 12:07 UTC
Im trying to press ALT on my windows pc keyboard - but only on keyup I get the result

lepik.on("keyPress",(data)=>{
  console.log(data) // Returns key pressed
})
lepik.on("keyUp",(data)=>{
  console.log(data) // Returns key released
})
lepik.on("keyDown",(data)=>{
  console.log(data) // Returns key holt
})

**Comment by DomEscobar** [comment] 2023-09-19 12:09
oh ups that belongs to lepikEvents

**Comment by Borecjeborec1** [comment] 2023-09-26 06:34
Don´t worry, it doesnť matter at all. _(Re: oh ups that belongs to lepikEvents)_

I am sorry for later response, currently a bit off and not updating at all.
I think I already know where the problem is, so I will look at it deeper ASAP and keep you updated :D.

Thanks for noticing this behavour!

**Comment by Borecjeborec1** [comment] 2023-09-26 06:48
Should be fixed in [LepikEvents v2.0.4+](https://www.npmjs.com/package/lepikevents) and  [LepikJS v3.3.0+](https://www.npmjs.com/package/lepikjs)


Feel free to test it :D.

Once again, thanks for noticing!

**Closed as completed by Borecjeborec1** 2023-09-26 06:48 UTC
